// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _2979b2970db79524da064298a61fd0f5_e9704cd5aa7b469eacf55a5f494ee42c : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity initiatingPlayer;
        }

        public static unsafe _2979b2970db79524da064298a61fd0f5_e9704cd5aa7b469eacf55a5f494ee42c FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for command with ID 28");
            }

            var orig = new _2979b2970db79524da064298a61fd0f5_e9704cd5aa7b469eacf55a5f494ee42c();
            var comp = (Interop*)data;
            orig.initiatingPlayer = comp->initiatingPlayer;
            return orig;
        }

        public Entity initiatingPlayer;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 28;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(initiatingPlayer, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.initiatingPlayer = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(initiatingPlayer, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.initiatingPlayer = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.initiatingPlayer,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.initiatingPlayer == entity) {
                this.initiatingPlayer = Entity.InvalidRelative;
            }
        }
        
        public _2979b2970db79524da064298a61fd0f5_e9704cd5aa7b469eacf55a5f494ee42c(
            Entity entity,
            Entity initiatingPlayer
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.initiatingPlayer = initiatingPlayer; 
        }
        
        public static void Serialize(_2979b2970db79524da064298a61fd0f5_e9704cd5aa7b469eacf55a5f494ee42c commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteEntity(commandData.initiatingPlayer);
        }
        
        public static _2979b2970db79524da064298a61fd0f5_e9704cd5aa7b469eacf55a5f494ee42c Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datainitiatingPlayer = bitStream.ReadEntity();
    
            return new _2979b2970db79524da064298a61fd0f5_e9704cd5aa7b469eacf55a5f494ee42c()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                initiatingPlayer = datainitiatingPlayer
            };   
        }
    }

}
