// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray stateName;
            [FieldOffset(16)]
            public System.Int32 layer;
        }

        public static unsafe _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 20) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 20) " +
                    "for command with ID 56");
            }

            var orig = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db();
            var comp = (Interop*)data;
            orig.stateName = comp->stateName.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->stateName.Data, (int)comp->stateName.Length) : null;
            orig.layer = comp->layer;
            return orig;
        }

        public System.String stateName;
        public System.Int32 layer;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 56;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db(
            Entity entity,
            System.String stateName,
            System.Int32 layer
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.stateName = stateName; 
            this.layer = layer; 
        }
        
        public static void Serialize(_a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteShortString(commandData.stateName);
            bitStream.WriteIntegerRange(commandData.layer, 32, -2147483648);
        }
        
        public static _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datastateName = bitStream.ReadShortString();
            var datalayer = bitStream.ReadIntegerRange(32, -2147483648);
    
            return new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                stateName = datastateName,
                layer = datalayer
            };   
        }
    }

}
