// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity heldItem;
            [FieldOffset(4)]
            public Entity inspectOrigin;
            [FieldOffset(8)]
            public System.Single inspectionDuration;
            [FieldOffset(12)]
            public System.Single inspectionRotationAmount;
            [FieldOffset(16)]
            public System.Byte enabled;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.heldItemMask;
            heldItemSimulationFrame = frame;
            FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.inspectOriginMask;
            inspectOriginSimulationFrame = frame;
            FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.inspectionDurationMask;
            inspectionDurationSimulationFrame = frame;
            FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.inspectionRotationAmountMask;
            inspectionRotationAmountSimulationFrame = frame;
            FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.enabledMask;
            enabledSimulationFrame = frame;
        }

        public static unsafe _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 17) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 17) " +
                    "for component with ID 18");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 18");
            }

            var orig = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778();

            var comp = (Interop*)data;

            orig.heldItem = comp->heldItem;
            orig.inspectOrigin = comp->inspectOrigin;
            orig.inspectionDuration = comp->inspectionDuration;
            orig.inspectionRotationAmount = comp->inspectionRotationAmount;
            orig.enabled = comp->enabled != 0;

            return orig;
        }


        public static uint heldItemMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame heldItemSimulationFrame;
        public Entity heldItem;
        public static uint inspectOriginMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame inspectOriginSimulationFrame;
        public Entity inspectOrigin;
        public static uint inspectionDurationMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame inspectionDurationSimulationFrame;
        public System.Single inspectionDuration;
        public static uint inspectionRotationAmountMask => 0b00000000000000000000000000001000;
        public AbsoluteSimulationFrame inspectionRotationAmountSimulationFrame;
        public System.Single inspectionRotationAmount;
        public static uint enabledMask => 0b00000000000000000000000000010000;
        public AbsoluteSimulationFrame enabledSimulationFrame;
        public System.Boolean enabled;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 18;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000011111;
        public bool HasFields() => true;
        public bool HasRefFields() => true;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 5;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return new HashSet<Entity>()
            {
                this.heldItem,
                this.inspectOrigin,
            };
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            uint refsMask = 0;

            if (this.heldItem == fromEntity)
            {
                this.heldItem = toEntity;
                refsMask |= 1 << 0;
            }
            if (this.inspectOrigin == fromEntity)
            {
                this.inspectOrigin = toEntity;
                refsMask |= 1 << 1;
            }

            FieldsMask |= refsMask;

            return refsMask;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            Entity absoluteEntity;
            IEntityMapper.Error err;
            err = mapper.MapToAbsoluteEntity(this.heldItem, false, out absoluteEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.heldItem = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(this.inspectOrigin, false, out absoluteEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.inspectOrigin = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            Entity relativeEntity;
            IEntityMapper.Error err;
            // We assume that the inConnection held changes with unresolved references, so the 'createMapping=true' is
            // there only because there's a chance that the parent creation change will be processed after this one
            // meaning there's no mapping for the parent yet. This wouldn't be necessary if mapping creation would happen
            // in the clientWorld via create/destroy requests while here we would only check whether mapping exists or not.
            var createParentMapping_heldItem = true;
            err = mapper.MapToRelativeEntity(this.heldItem, createParentMapping_heldItem,
             out relativeEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.heldItem = relativeEntity;
            // We assume that the inConnection held changes with unresolved references, so the 'createMapping=true' is
            // there only because there's a chance that the parent creation change will be processed after this one
            // meaning there's no mapping for the parent yet. This wouldn't be necessary if mapping creation would happen
            // in the clientWorld via create/destroy requests while here we would only check whether mapping exists or not.
            var createParentMapping_inspectOrigin = true;
            err = mapper.MapToRelativeEntity(this.inspectOrigin, createParentMapping_inspectOrigin,
             out relativeEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.inspectOrigin = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.heldItemSimulationFrame = other.heldItemSimulationFrame;
                this.heldItem = other.heldItem;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.inspectOriginSimulationFrame = other.inspectOriginSimulationFrame;
                this.inspectOrigin = other.inspectOrigin;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.inspectionDurationSimulationFrame = other.inspectionDurationSimulationFrame;
                this.inspectionDuration = other.inspectionDuration;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.inspectionRotationAmountSimulationFrame = other.inspectionRotationAmountSimulationFrame;
                this.inspectionRotationAmount = other.inspectionRotationAmount;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.enabledSimulationFrame = other.enabledSimulationFrame;
                this.enabled = other.enabled;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 5);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.heldItem;
                bitStream.WriteEntity(fieldValue);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.inspectOrigin;
                bitStream.WriteEntity(fieldValue);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.inspectionDuration;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.inspectionRotationAmount;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.enabled;
                bitStream.WriteBool(fieldValue);
            }
            mask >>= 1;

            return mask;
        }

        public static _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(5);
            }

            var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778();
            if (bitStream.ReadMask())
            {

                val.heldItem = bitStream.ReadEntity();
                val.FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.heldItemMask;
            }
            if (bitStream.ReadMask())
            {

                val.inspectOrigin = bitStream.ReadEntity();
                val.FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.inspectOriginMask;
            }
            if (bitStream.ReadMask())
            {

                val.inspectionDuration = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.inspectionDurationMask;
            }
            if (bitStream.ReadMask())
            {

                val.inspectionRotationAmount = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.inspectionRotationAmountMask;
            }
            if (bitStream.ReadMask())
            {

                val.enabled = bitStream.ReadBool();
                val.FieldsMask |= _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778.enabledMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_a1fa7cddf5d5ef94b8bacf8838c9a6fa_2185722752081631778(" +
                $" heldItem: { this.heldItem }" +
                $" inspectOrigin: { this.inspectOrigin }" +
                $" inspectionDuration: { this.inspectionDuration }" +
                $" inspectionRotationAmount: { this.inspectionRotationAmount }" +
                $" enabled: { this.enabled }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(5, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(5, '0') })";
        }
    }

}
