// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Text;
    using Coherence;
    using Coherence.Brisk;
    using Coherence.ProtocolDef;
    using Coherence.Connection;
    using Coherence.Entities;
    using System.Collections.Generic;
    using Coherence.SimulationFrame;
    using Coherence.Core;

    public class DataInteropHandler : IDataInteropHandler
    {
        public unsafe ICoherenceComponentData GetComponent(UInt32 type, IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            switch(type)
            {
                case 0: return WorldPosition.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 1: return WorldOrientation.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 2: return LocalUserComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 3: return WorldPositionQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 4: return ArchetypeComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 5: return Persistence.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 6: return ConnectedEntity.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 7: return UniqueID.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 8: return Connection.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 9: return ConnectionScene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 10: return Global.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 11: return GlobalQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 12: return Tag.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 13: return TagQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 14: return PreserveChildren.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 15: return Scene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 16: return AssetId.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 17: return GenericScale.FromInterop(data, dataSize, simFrames, simFramesCount);
            }

            throw new ArgumentException($"Unkown component type {type}", nameof(type));
        }

        public unsafe void UpdateComponent(INativeCoreComponentUpdater updater, InteropEntity entity, ICoherenceComponentData component)
        {
            var componentType = component.GetComponentType();
            var frames = component.GetSimulationFrames();

            switch (componentType)
            {
                case 0:
                {
                    var orig = (WorldPosition)component;
                    var val = new WorldPosition.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 1:
                {
                    var orig = (WorldOrientation)component;
                    var val = new WorldOrientation.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 2:
                {
                    var orig = (LocalUserComponent)component;
                    var val = new LocalUserComponent.Interop();

                    val.localIndex = orig.localIndex;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 3:
                {
                    var orig = (WorldPositionQuery)component;
                    var val = new WorldPositionQuery.Interop();

                    val.position = orig.position;
                    val.radius = orig.radius;
                    val.buffer = orig.buffer;

                    updater.UpdateComponent(entity, componentType, val, 20, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 4:
                {
                    var orig = (ArchetypeComponent)component;
                    var val = new ArchetypeComponent.Interop();

                    val.index = orig.index;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 5:
                {
                    var orig = (Persistence)component;
                    var val = new Persistence.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 6:
                {
                    var orig = (ConnectedEntity)component;
                    var val = new ConnectedEntity.Interop();

                    val.value = orig.value;
                    val.pos = orig.pos;
                    val.rot = orig.rot;
                    val.scale = orig.scale;

                    updater.UpdateComponent(entity, componentType, val, 44, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 7:
                {
                    var orig = (UniqueID)component;
                    var val = new UniqueID.Interop();

                    var pinneduuid = orig.uuid != null ? Encoding.UTF8.GetBytes(orig.uuid) : null; fixed (void* pinnedPtruuid = pinneduuid) { val.uuid = new ByteArray { Data = pinnedPtruuid, Length =  pinneduuid?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 8:
                {
                    var orig = (Connection)component;
                    var val = new Connection.Interop();

                    val.id = orig.id;
                    val.type = orig.type;

                    updater.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 9:
                {
                    var orig = (ConnectionScene)component;
                    var val = new ConnectionScene.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 10:
                {
                    var orig = (Global)component;
                    var val = new Global.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 11:
                {
                    var orig = (GlobalQuery)component;
                    var val = new GlobalQuery.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 12:
                {
                    var orig = (Tag)component;
                    var val = new Tag.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 13:
                {
                    var orig = (TagQuery)component;
                    var val = new TagQuery.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 14:
                {
                    var orig = (PreserveChildren)component;
                    var val = new PreserveChildren.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 15:
                {
                    var orig = (Scene)component;
                    var val = new Scene.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 16:
                {
                    var orig = (AssetId)component;
                    var val = new AssetId.Interop();

                    val.value = orig.value;
                    val.isFromGroup = orig.isFromGroup ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 5, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 17:
                {
                    var orig = (GenericScale)component;
                    var val = new GenericScale.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
            }

            throw new NotImplementedException($"Failed to update a component with type {componentType}.");
        }

        public unsafe IEntityCommand GetCommand(UInt32 type, IntPtr data, Int32 dataSize)
        {
            switch (type)
            {
                  case 0: return AuthorityRequest.FromInterop(data, dataSize);
                  case 1: return AuthorityTransfer.FromInterop(data, dataSize);
                  case 2: return QuerySynced.FromInterop(data, dataSize);
                  case 3: return AdoptOrphan.FromInterop(data, dataSize);
                  case 4: return PersistenceReady.FromInterop(data, dataSize);
                  case 5: return SceneIndexChanged.FromInterop(data, dataSize);
                  case 6: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_0abcbd9f234748568fd3cf0c0d4015e0.FromInterop(data, dataSize);
                  case 7: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_0e4326067c3a48908e9f4b9460208b7e.FromInterop(data, dataSize);
                  case 8: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db.FromInterop(data, dataSize);
                  case 9: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_162511d5b5314af3a48dc608a33cbf93.FromInterop(data, dataSize);
                  case 10: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_1e2e594b7cf84ccb9dde946343d87212.FromInterop(data, dataSize);
                  case 11: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2283c1247ea64c1db1c8b3e173e89139.FromInterop(data, dataSize);
                  case 12: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_26e718996e4b4ed9a118f1465eec38df.FromInterop(data, dataSize);
                  case 13: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_27a87add317b4311909e77f5e889bcc9.FromInterop(data, dataSize);
                  case 14: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_27c844bca78c44a180298a31aa77b3e0.FromInterop(data, dataSize);
                  case 15: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2c3bc9b5dc68465ab589a5ea764a7434.FromInterop(data, dataSize);
                  case 16: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_34fddbd082cf40d0946240816f67bb36.FromInterop(data, dataSize);
                  case 17: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_354718ff04d64fefad2b2186b162dc16.FromInterop(data, dataSize);
                  case 18: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_3918d4656e384d0eaba7b46782de7267.FromInterop(data, dataSize);
                  case 19: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_406ab4a9d5154d819ed1b58f1691204d.FromInterop(data, dataSize);
                  case 20: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_41ba3a465b1b4141a56bf2d84a86b5dd.FromInterop(data, dataSize);
                  case 21: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_4484767958be4480a28cfa0dc4fe879f.FromInterop(data, dataSize);
                  case 22: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_4cad330df3b041179eff4cb8ab5129ff.FromInterop(data, dataSize);
                  case 23: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_500f72bfdc014d6782a007c4aa45840b.FromInterop(data, dataSize);
                  case 24: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_603bbcc77d4b47ebac12e74f6482cb0e.FromInterop(data, dataSize);
                  case 25: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_608df35b7d454a5283994961765e1033.FromInterop(data, dataSize);
                  case 26: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_6684c57b4da54db0a052a3fe8b036b3f.FromInterop(data, dataSize);
                  case 27: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_776bd05e4f9b47a4bac0bdece67c291d.FromInterop(data, dataSize);
                  case 28: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_7a1960a7b48e442d8ab6f55ec1fa366a.FromInterop(data, dataSize);
                  case 29: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_877b905e0630402ca0a0b932bffc3d03.FromInterop(data, dataSize);
                  case 30: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_8e00e7ff7c1e4edf94510bb16afe5972.FromInterop(data, dataSize);
                  case 31: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_91e03de64fe54dcaa294b22f1e9ddf3a.FromInterop(data, dataSize);
                  case 32: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_970f10b12056470cb3bdcb94a59c2589.FromInterop(data, dataSize);
                  case 33: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_a4cb52e3f7df4c398d7b6d82556866f4.FromInterop(data, dataSize);
                  case 34: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_af125522109d4409b46634431fd819ea.FromInterop(data, dataSize);
                  case 35: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_b863d056c97d47fba178c858a64d1b5f.FromInterop(data, dataSize);
                  case 36: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_c45d945bfa7749d39511f8ca8d7ae361.FromInterop(data, dataSize);
                  case 37: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_ce384ff9c5034caf97abaafdc07d6fd6.FromInterop(data, dataSize);
                  case 38: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_d5a8bf58b0e54974a9ddde324b0aa64c.FromInterop(data, dataSize);
                  case 39: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_d6f23f679e094762b3749e480f971cb9.FromInterop(data, dataSize);
                  case 40: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_e4859c2ffb8a48fcb7b07a710a131b1e.FromInterop(data, dataSize);
                  case 41: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_fb661e6b1f774146a948e90e5b5adbf9.FromInterop(data, dataSize);
                  case 42: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa_fedb9c11aaff482dafe28f87e3407817.FromInterop(data, dataSize);
                  case 43: return _e27de4a604e9ea443863c3dd92c22069_5ca8468799f04bb08cf3b81f0036144b.FromInterop(data, dataSize);
                  case 44: return _e27de4a604e9ea443863c3dd92c22069_81b31f8e7a2d48bd9fdf573e9e783497.FromInterop(data, dataSize);
                  case 45: return _e27de4a604e9ea443863c3dd92c22069_8d2fc773b92445ada86a4dd1ccf2f71f.FromInterop(data, dataSize);
                  case 46: return _e27de4a604e9ea443863c3dd92c22069_af006724d82d470981eb91ecfd58b9ef.FromInterop(data, dataSize);
                  case 47: return _e27de4a604e9ea443863c3dd92c22069_c67e044ec7e140f2a8961a0cbe05892c.FromInterop(data, dataSize);
                  case 48: return _e27de4a604e9ea443863c3dd92c22069_e03ce5cf0e6243a4af4fb1e2247252d5.FromInterop(data, dataSize);
                  case 49: return _e27de4a604e9ea443863c3dd92c22069_ebdaa5e2280e44f4881ab63c7de64b1a.FromInterop(data, dataSize);
                  case 50: return _e27de4a604e9ea443863c3dd92c22069_f91bd6ef360d4258972f3a65c1445538.FromInterop(data, dataSize);
            }

            throw new ArgumentException($"Unkown command type {type}", nameof(type));
        }

        public unsafe IEntityInput GetInput(UInt32 type, IntPtr data, Int32 dataSize)
        {
            switch (type)
            {
                  case 0: return _a1fa7cddf5d5ef94b8bacf8838c9a6fa.FromInterop(data, dataSize);
            }
            throw new ArgumentException($"Unknown input type {type}", nameof(type));
        }

        public unsafe bool SendCommand(INativeCoreCommandSender sender, InteropEntity entity, MessageTarget target, IEntityCommand command)
        {
            var type = command.GetComponentType();
            switch (type)
            {
                case 0:
                {
                    var orig = (AuthorityRequest)command;
                    var val = new AuthorityRequest.Interop();

                    val.requester = orig.requester;
                    val.authorityType = orig.authorityType;

                    return sender.SendCommand(entity, target, type, val, 8);

                }
                case 1:
                {
                    var orig = (AuthorityTransfer)command;
                    var val = new AuthorityTransfer.Interop();

                    val.newAuthority = orig.newAuthority;
                    val.accepted = orig.accepted ? (System.Byte)1 : (System.Byte)0;
                    val.authorityType = orig.authorityType;

                    return sender.SendCommand(entity, target, type, val, 9);

                }
                case 2:
                {
                    var orig = (QuerySynced)command;
                    var val = new QuerySynced.Interop();

                    val.liveQuerySynced = orig.liveQuerySynced ? (System.Byte)1 : (System.Byte)0;
                    val.globalQuerySynced = orig.globalQuerySynced ? (System.Byte)1 : (System.Byte)0;

                    return sender.SendCommand(entity, target, type, val, 2);

                }
                case 3:
                {
                    var orig = (AdoptOrphan)command;
                    var val = new AdoptOrphan.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 4:
                {
                    var orig = (PersistenceReady)command;
                    var val = new PersistenceReady.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 5:
                {
                    var orig = (SceneIndexChanged)command;
                    var val = new SceneIndexChanged.Interop();

                    val.sceneIndex = orig.sceneIndex;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 6:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_0abcbd9f234748568fd3cf0c0d4015e0)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_0abcbd9f234748568fd3cf0c0d4015e0.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };

                    return sender.SendCommand(entity, target, type, val, 16);

}                }
                case 7:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_0e4326067c3a48908e9f4b9460208b7e)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_0e4326067c3a48908e9f4b9460208b7e.Interop();

                    var pinnedstateName = orig.stateName != null ? Encoding.UTF8.GetBytes(orig.stateName) : null; fixed (void* pinnedPtrstateName = pinnedstateName) { val.stateName = new ByteArray { Data = pinnedPtrstateName, Length =  pinnedstateName?.Length ?? 0 };
                    val.layer = orig.layer;
                    val.normalizedTime = orig.normalizedTime;

                    return sender.SendCommand(entity, target, type, val, 24);

}                }
                case 8:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_14a556098e364510ab2ad96e990fd5db.Interop();

                    var pinnedstateName = orig.stateName != null ? Encoding.UTF8.GetBytes(orig.stateName) : null; fixed (void* pinnedPtrstateName = pinnedstateName) { val.stateName = new ByteArray { Data = pinnedPtrstateName, Length =  pinnedstateName?.Length ?? 0 };
                    val.layer = orig.layer;

                    return sender.SendCommand(entity, target, type, val, 20);

}                }
                case 9:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_162511d5b5314af3a48dc608a33cbf93)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_162511d5b5314af3a48dc608a33cbf93.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 10:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_1e2e594b7cf84ccb9dde946343d87212)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_1e2e594b7cf84ccb9dde946343d87212.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 11:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_2283c1247ea64c1db1c8b3e173e89139)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2283c1247ea64c1db1c8b3e173e89139.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 12:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_26e718996e4b4ed9a118f1465eec38df)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_26e718996e4b4ed9a118f1465eec38df.Interop();

                    var pinnedstateName = orig.stateName != null ? Encoding.UTF8.GetBytes(orig.stateName) : null; fixed (void* pinnedPtrstateName = pinnedstateName) { val.stateName = new ByteArray { Data = pinnedPtrstateName, Length =  pinnedstateName?.Length ?? 0 };
                    val.layer = orig.layer;
                    val.fixedTime = orig.fixedTime;

                    return sender.SendCommand(entity, target, type, val, 24);

}                }
                case 13:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_27a87add317b4311909e77f5e889bcc9)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_27a87add317b4311909e77f5e889bcc9.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 14:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_27c844bca78c44a180298a31aa77b3e0)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_27c844bca78c44a180298a31aa77b3e0.Interop();

                    val.initiatingPlayerSync = orig.initiatingPlayerSync;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 15:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_2c3bc9b5dc68465ab589a5ea764a7434)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_2c3bc9b5dc68465ab589a5ea764a7434.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 16:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_34fddbd082cf40d0946240816f67bb36)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_34fddbd082cf40d0946240816f67bb36.Interop();

                    val.stateNameHash = orig.stateNameHash;
                    val.layer = orig.layer;

                    return sender.SendCommand(entity, target, type, val, 8);

                }
                case 17:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_354718ff04d64fefad2b2186b162dc16)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_354718ff04d64fefad2b2186b162dc16.Interop();

                    val.initiatingPlayerSync = orig.initiatingPlayerSync;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 18:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_3918d4656e384d0eaba7b46782de7267)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_3918d4656e384d0eaba7b46782de7267.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 19:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_406ab4a9d5154d819ed1b58f1691204d)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_406ab4a9d5154d819ed1b58f1691204d.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 20:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_41ba3a465b1b4141a56bf2d84a86b5dd)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_41ba3a465b1b4141a56bf2d84a86b5dd.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 21:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_4484767958be4480a28cfa0dc4fe879f)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_4484767958be4480a28cfa0dc4fe879f.Interop();

                    val.stateNameHash = orig.stateNameHash;
                    val.layer = orig.layer;
                    val.normalizedTime = orig.normalizedTime;

                    return sender.SendCommand(entity, target, type, val, 12);

                }
                case 22:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_4cad330df3b041179eff4cb8ab5129ff)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_4cad330df3b041179eff4cb8ab5129ff.Interop();

                    var pinnedstateName = orig.stateName != null ? Encoding.UTF8.GetBytes(orig.stateName) : null; fixed (void* pinnedPtrstateName = pinnedstateName) { val.stateName = new ByteArray { Data = pinnedPtrstateName, Length =  pinnedstateName?.Length ?? 0 };

                    return sender.SendCommand(entity, target, type, val, 16);

}                }
                case 23:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_500f72bfdc014d6782a007c4aa45840b)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_500f72bfdc014d6782a007c4aa45840b.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 24:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_603bbcc77d4b47ebac12e74f6482cb0e)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_603bbcc77d4b47ebac12e74f6482cb0e.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 25:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_608df35b7d454a5283994961765e1033)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_608df35b7d454a5283994961765e1033.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 26:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_6684c57b4da54db0a052a3fe8b036b3f)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_6684c57b4da54db0a052a3fe8b036b3f.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;
                    val.interactionType = orig.interactionType;

                    return sender.SendCommand(entity, target, type, val, 8);

                }
                case 27:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_776bd05e4f9b47a4bac0bdece67c291d)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_776bd05e4f9b47a4bac0bdece67c291d.Interop();

                    val.initiatingPlayerSync = orig.initiatingPlayerSync;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 28:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_7a1960a7b48e442d8ab6f55ec1fa366a)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_7a1960a7b48e442d8ab6f55ec1fa366a.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 29:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_877b905e0630402ca0a0b932bffc3d03)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_877b905e0630402ca0a0b932bffc3d03.Interop();

                    var pinnedstateName = orig.stateName != null ? Encoding.UTF8.GetBytes(orig.stateName) : null; fixed (void* pinnedPtrstateName = pinnedstateName) { val.stateName = new ByteArray { Data = pinnedPtrstateName, Length =  pinnedstateName?.Length ?? 0 };
                    val.layer = orig.layer;

                    return sender.SendCommand(entity, target, type, val, 20);

}                }
                case 30:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_8e00e7ff7c1e4edf94510bb16afe5972)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_8e00e7ff7c1e4edf94510bb16afe5972.Interop();

                    val.id = orig.id;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 31:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_91e03de64fe54dcaa294b22f1e9ddf3a)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_91e03de64fe54dcaa294b22f1e9ddf3a.Interop();

                    val.stateNameHash = orig.stateNameHash;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 32:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_970f10b12056470cb3bdcb94a59c2589)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_970f10b12056470cb3bdcb94a59c2589.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 33:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_a4cb52e3f7df4c398d7b6d82556866f4)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_a4cb52e3f7df4c398d7b6d82556866f4.Interop();

                    val.stateNameHash = orig.stateNameHash;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 34:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_af125522109d4409b46634431fd819ea)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_af125522109d4409b46634431fd819ea.Interop();

                    val.initiatingPlayerSync = orig.initiatingPlayerSync;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 35:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_b863d056c97d47fba178c858a64d1b5f)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_b863d056c97d47fba178c858a64d1b5f.Interop();

                    val.id = orig.id;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 36:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_c45d945bfa7749d39511f8ca8d7ae361)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_c45d945bfa7749d39511f8ca8d7ae361.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 37:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_ce384ff9c5034caf97abaafdc07d6fd6)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_ce384ff9c5034caf97abaafdc07d6fd6.Interop();

                    var pinnedname = orig.name != null ? Encoding.UTF8.GetBytes(orig.name) : null; fixed (void* pinnedPtrname = pinnedname) { val.name = new ByteArray { Data = pinnedPtrname, Length =  pinnedname?.Length ?? 0 };

                    return sender.SendCommand(entity, target, type, val, 16);

}                }
                case 38:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_d5a8bf58b0e54974a9ddde324b0aa64c)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_d5a8bf58b0e54974a9ddde324b0aa64c.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 39:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_d6f23f679e094762b3749e480f971cb9)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_d6f23f679e094762b3749e480f971cb9.Interop();

                    var pinnedstateName = orig.stateName != null ? Encoding.UTF8.GetBytes(orig.stateName) : null; fixed (void* pinnedPtrstateName = pinnedstateName) { val.stateName = new ByteArray { Data = pinnedPtrstateName, Length =  pinnedstateName?.Length ?? 0 };

                    return sender.SendCommand(entity, target, type, val, 16);

}                }
                case 40:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_e4859c2ffb8a48fcb7b07a710a131b1e)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_e4859c2ffb8a48fcb7b07a710a131b1e.Interop();

                    val.stateNameHash = orig.stateNameHash;
                    val.layer = orig.layer;
                    val.fixedTime = orig.fixedTime;

                    return sender.SendCommand(entity, target, type, val, 12);

                }
                case 41:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_fb661e6b1f774146a948e90e5b5adbf9)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_fb661e6b1f774146a948e90e5b5adbf9.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 42:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa_fedb9c11aaff482dafe28f87e3407817)command;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa_fedb9c11aaff482dafe28f87e3407817.Interop();

                    val.stateNameHash = orig.stateNameHash;
                    val.layer = orig.layer;

                    return sender.SendCommand(entity, target, type, val, 8);

                }
                case 43:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_5ca8468799f04bb08cf3b81f0036144b)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_5ca8468799f04bb08cf3b81f0036144b.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 44:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_81b31f8e7a2d48bd9fdf573e9e783497)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_81b31f8e7a2d48bd9fdf573e9e783497.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 45:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_8d2fc773b92445ada86a4dd1ccf2f71f)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_8d2fc773b92445ada86a4dd1ccf2f71f.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 46:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_af006724d82d470981eb91ecfd58b9ef)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_af006724d82d470981eb91ecfd58b9ef.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 47:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_c67e044ec7e140f2a8961a0cbe05892c)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_c67e044ec7e140f2a8961a0cbe05892c.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 48:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_e03ce5cf0e6243a4af4fb1e2247252d5)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_e03ce5cf0e6243a4af4fb1e2247252d5.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 49:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_ebdaa5e2280e44f4881ab63c7de64b1a)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_ebdaa5e2280e44f4881ab63c7de64b1a.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 50:
                {
                    var orig = (_e27de4a604e9ea443863c3dd92c22069_f91bd6ef360d4258972f3a65c1445538)command;
                    var val = new _e27de4a604e9ea443863c3dd92c22069_f91bd6ef360d4258972f3a65c1445538.Interop();

                    val.initiatingPlayer = orig.initiatingPlayer;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
            }

            throw new NotImplementedException($"Failed to send a command with type {type}.");
        }

        public unsafe void SendInput(INativeCoreInputSender sender, InteropEntity entity, long frame, IEntityInput input)
        {
            var type = input.GetComponentType();
            var inputData = (InputData)input;
            switch (type)
            {
                case 0:
                {
                    var orig = (_a1fa7cddf5d5ef94b8bacf8838c9a6fa)inputData.Input;
                    var val = new _a1fa7cddf5d5ef94b8bacf8838c9a6fa.Interop();


                    sender.SendInput(entity, frame, type, val, 0);

                    return;
                }
            }

            throw new NotImplementedException($"Failed to send an input with type {type}.");
        }
    }

}
