// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_cd55199613c8b184e879d7bae921a108_9725f6f302e3428f98487df72ae65c75 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_cd55199613c8b184e879d7bae921a108 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_cd55199613c8b184e879d7bae921a108>();
        
        private global::Interactable _cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba_CommandTarget;
        private global::Interactable _cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695_CommandTarget;
        private global::Interactable _cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c_CommandTarget;
        private global::Interactable _cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09_CommandTarget;
        private global::Interactable _cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b_CommandTarget;
        private global::Interactable _cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864_CommandTarget;
        private global::Interactable _cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98_CommandTarget;
        private global::Interactable _cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["9725f6f302e3428f98487df72ae65c75"] = new Binding_cd55199613c8b184e879d7bae921a108_9725f6f302e3428f98487df72ae65c75(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_cd55199613c8b184e879d7bae921a108()
        {
            bakedCommandBindings.Add("6e56085a66a2415698f92fabc4bf7bba", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba);
            bakedCommandBindings.Add("d3c3c431cc644765bac6264f325e5695", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695);
            bakedCommandBindings.Add("54c945ce611c4b9c904d0c97a0130c0c", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c);
            bakedCommandBindings.Add("07e377b8061c48f49f00e79e42ddbd09", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09);
            bakedCommandBindings.Add("1c3f13a17fcd4cff9582cc975c04c69b", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b);
            bakedCommandBindings.Add("7793c66d1c6e46aa8d87a365a825d864", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864);
            bakedCommandBindings.Add("94232860fa5a4756be8ce27ed5f11a98", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98);
            bakedCommandBindings.Add("eb005deffe204d2bb391cdd6924e0ca3", BakeCommandBinding__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestCollect",
            	"(UnityEngine.GameObject)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba(_cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba_CommandTarget;
			target.RequestCollect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestInspect",
            	"(UnityEngine.GameObject)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695(_cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695 command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695_CommandTarget;
			target.RequestInspect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestMurder",
            	"(UnityEngine.GameObject)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c(_cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c_CommandTarget;
			target.RequestMurder(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestScare",
            	"(UnityEngine.GameObject)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09(_cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09 command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09_CommandTarget;
			target.RequestScare(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnScare",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b(_cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b_CommandTarget;
			target.OnScare(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnMurder",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864(_cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864 command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864_CommandTarget;
			target.OnMurder(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnInspect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98(_cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98 command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98_CommandTarget;
			target.OnInspect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnCollect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3,
            	ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3,
            	MessageTarget.All,
            	_cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3(GenericCommandRequestArgs requestArgs)
        {
            var command = new _cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3(command);
        }

        private void ReceiveCommand__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3(_cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3 command)
        {
            var target = _cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3_CommandTarget;
			target.OnCollect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_6e56085a66a2415698f92fabc4bf7bba(castedCommand);
                    break;
                case _cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695 castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_d3c3c431cc644765bac6264f325e5695(castedCommand);
                    break;
                case _cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_54c945ce611c4b9c904d0c97a0130c0c(castedCommand);
                    break;
                case _cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09 castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_07e377b8061c48f49f00e79e42ddbd09(castedCommand);
                    break;
                case _cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_1c3f13a17fcd4cff9582cc975c04c69b(castedCommand);
                    break;
                case _cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864 castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_7793c66d1c6e46aa8d87a365a825d864(castedCommand);
                    break;
                case _cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98 castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_94232860fa5a4756be8ce27ed5f11a98(castedCommand);
                    break;
                case _cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3 castedCommand:
                    ReceiveCommand__cd55199613c8b184e879d7bae921a108_eb005deffe204d2bb391cdd6924e0ca3(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_cd55199613c8b184e879d7bae921a108 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_cd55199613c8b184e879d7bae921a108>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
