// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_09a3cf2fc0f6dc340bab238a1f23cad5_4bff8f7ad74b4e8bb071be5595921cf7 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_09a3cf2fc0f6dc340bab238a1f23cad5_55053cba0fbd4c0ca6e21a99ef75bfcb : EnumBinding
    {   
        private global::Managers.GameManager CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Managers.GameManager)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704);
        public override string CoherenceComponentName => "_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)CastedUnityComponent.CurrentState; }
            set { CastedUnityComponent.CurrentState = (Managers.GameState)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704)coherenceComponent).CurrentState;

            var simFrame = ((_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704)coherenceComponent).CurrentStateSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.CurrentState = Value;
            }
            else
            {
                update.CurrentState = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.CurrentStateSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_09a3cf2fc0f6dc340bab238a1f23cad5_d26e7ff8ffae4d09bdb4394d15f63ec4 : StringBinding
    {   
        private global::Managers.GameManager CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Managers.GameManager)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704);
        public override string CoherenceComponentName => "_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.WinnerId); }
            set { CastedUnityComponent.WinnerId = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704)coherenceComponent).WinnerId;

            var simFrame = ((_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704)coherenceComponent).WinnerIdSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.WinnerId = Value;
            }
            else
            {
                update.WinnerId = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.WinnerIdSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _09a3cf2fc0f6dc340bab238a1f23cad5_7517697408792799704();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_09a3cf2fc0f6dc340bab238a1f23cad5 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_09a3cf2fc0f6dc340bab238a1f23cad5>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["4bff8f7ad74b4e8bb071be5595921cf7"] = new Binding_09a3cf2fc0f6dc340bab238a1f23cad5_4bff8f7ad74b4e8bb071be5595921cf7(),
			["55053cba0fbd4c0ca6e21a99ef75bfcb"] = new Binding_09a3cf2fc0f6dc340bab238a1f23cad5_55053cba0fbd4c0ca6e21a99ef75bfcb(),
			["d26e7ff8ffae4d09bdb4394d15f63ec4"] = new Binding_09a3cf2fc0f6dc340bab238a1f23cad5_d26e7ff8ffae4d09bdb4394d15f63ec4(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_09a3cf2fc0f6dc340bab238a1f23cad5()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_09a3cf2fc0f6dc340bab238a1f23cad5 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_09a3cf2fc0f6dc340bab238a1f23cad5>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
