// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_15368d1dc47e40c47bfa22cdc4f793a0_bb537f43ad87456585cdd4b74e76e745 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_15368d1dc47e40c47bfa22cdc4f793a0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_15368d1dc47e40c47bfa22cdc4f793a0>();
        
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b_CommandTarget;
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4_CommandTarget;
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7_CommandTarget;
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec_CommandTarget;
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062_CommandTarget;
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0_CommandTarget;
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3_CommandTarget;
        private global::Interactable _15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["bb537f43ad87456585cdd4b74e76e745"] = new Binding_15368d1dc47e40c47bfa22cdc4f793a0_bb537f43ad87456585cdd4b74e76e745(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_15368d1dc47e40c47bfa22cdc4f793a0()
        {
            bakedCommandBindings.Add("532293bb188644d7a1ceb1a41b76b13b", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b);
            bakedCommandBindings.Add("e090eebb5a1d41e1a1069c1fd80eb9b4", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4);
            bakedCommandBindings.Add("4191398910ce4921b04a0ed36c9074d7", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7);
            bakedCommandBindings.Add("e4f6202d543147aebfdcf0b7e7654aec", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec);
            bakedCommandBindings.Add("eeb88b6db6994dd48ef113698fa10062", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062);
            bakedCommandBindings.Add("08800c0175c2419a942b654d22ea21e0", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0);
            bakedCommandBindings.Add("94665d9e130e4aef94268b9498a635c3", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3);
            bakedCommandBindings.Add("78ba064a0bd143fa88434cd80e4e8c3a", BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestCollect",
            	"(UnityEngine.GameObject)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b(_15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b_CommandTarget;
			target.RequestCollect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestInspect",
            	"(UnityEngine.GameObject)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4(_15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4 command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4_CommandTarget;
			target.RequestInspect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestMurder",
            	"(UnityEngine.GameObject)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7(_15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7 command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7_CommandTarget;
			target.RequestMurder(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestScare",
            	"(UnityEngine.GameObject)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec(_15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec_CommandTarget;
			target.RequestScare(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnScare",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062(_15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062 command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062_CommandTarget;
			target.OnScare(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnMurder",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0(_15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0 command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0_CommandTarget;
			target.OnMurder(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnInspect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3(_15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3 command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3_CommandTarget;
			target.OnInspect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnCollect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a,
            	ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a,
            	MessageTarget.All,
            	_15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a(GenericCommandRequestArgs requestArgs)
        {
            var command = new _15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a(command);
        }

        private void ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a(_15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a command)
        {
            var target = _15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a_CommandTarget;
			target.OnCollect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_532293bb188644d7a1ceb1a41b76b13b(castedCommand);
                    break;
                case _15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4 castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_e090eebb5a1d41e1a1069c1fd80eb9b4(castedCommand);
                    break;
                case _15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7 castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_4191398910ce4921b04a0ed36c9074d7(castedCommand);
                    break;
                case _15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_e4f6202d543147aebfdcf0b7e7654aec(castedCommand);
                    break;
                case _15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062 castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_eeb88b6db6994dd48ef113698fa10062(castedCommand);
                    break;
                case _15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0 castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_08800c0175c2419a942b654d22ea21e0(castedCommand);
                    break;
                case _15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3 castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_94665d9e130e4aef94268b9498a635c3(castedCommand);
                    break;
                case _15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a castedCommand:
                    ReceiveCommand__15368d1dc47e40c47bfa22cdc4f793a0_78ba064a0bd143fa88434cd80e4e8c3a(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_15368d1dc47e40c47bfa22cdc4f793a0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_15368d1dc47e40c47bfa22cdc4f793a0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
