// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_e61c5d2dfc4521841997842ff9788719_3a4ed752b8cd4026a31889d0b4e8ec3a : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_e61c5d2dfc4521841997842ff9788719 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_e61c5d2dfc4521841997842ff9788719>();
        
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724_CommandTarget;
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3_CommandTarget;
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918_CommandTarget;
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1_CommandTarget;
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42_CommandTarget;
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b_CommandTarget;
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818_CommandTarget;
        private global::Interactable _e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc_CommandTarget;
        
        private InputBuffer<_e61c5d2dfc4521841997842ff9788719> inputBuffer;
        private _e61c5d2dfc4521841997842ff9788719 currentInput;
        private long lastAddedFrame = -1;
        private CoherenceInput coherenceInput;
        private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["3a4ed752b8cd4026a31889d0b4e8ec3a"] = new Binding_e61c5d2dfc4521841997842ff9788719_3a4ed752b8cd4026a31889d0b4e8ec3a(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_e61c5d2dfc4521841997842ff9788719()
        {
            bakedCommandBindings.Add("c57dca2108b34d52ba77f5492db83724", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724);
            bakedCommandBindings.Add("0d3b076037114596b45f30e8cc99cae3", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3);
            bakedCommandBindings.Add("b51ecda486b34706b4e3fd50e3588918", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918);
            bakedCommandBindings.Add("9949bdc434714688b8443706dc782de1", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1);
            bakedCommandBindings.Add("c5855f1288bc499781853acc32d7af42", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42);
            bakedCommandBindings.Add("1731ecb264ce4966ba517250ad49ce4b", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b);
            bakedCommandBindings.Add("b29cf77c85a949cf95c7c84b649d2818", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818);
            bakedCommandBindings.Add("0f0bd3ed1c5d4c978612ca7d8365fafc", BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestCollect",
            	"(UnityEngine.GameObject)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724(_e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724 command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724_CommandTarget;
			target.RequestCollect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestInspect",
            	"(UnityEngine.GameObject)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3(_e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3 command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3_CommandTarget;
			target.RequestInspect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestMurder",
            	"(UnityEngine.GameObject)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918(_e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918 command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918_CommandTarget;
			target.RequestMurder(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestScare",
            	"(UnityEngine.GameObject)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1(_e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1 command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1_CommandTarget;
			target.RequestScare(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnScare",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42(_e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42 command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42_CommandTarget;
			target.OnScare(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnMurder",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b(_e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b_CommandTarget;
			target.OnMurder(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnInspect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818(_e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818 command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818_CommandTarget;
			target.OnInspect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnCollect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc,
            	ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc,
            	MessageTarget.All,
            	_e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc(command);
        }

        private void ReceiveCommand__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc(_e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc command)
        {
            var target = _e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc_CommandTarget;
			target.OnCollect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724 castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_c57dca2108b34d52ba77f5492db83724(castedCommand);
                    break;
                case _e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3 castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_0d3b076037114596b45f30e8cc99cae3(castedCommand);
                    break;
                case _e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918 castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_b51ecda486b34706b4e3fd50e3588918(castedCommand);
                    break;
                case _e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1 castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_9949bdc434714688b8443706dc782de1(castedCommand);
                    break;
                case _e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42 castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_c5855f1288bc499781853acc32d7af42(castedCommand);
                    break;
                case _e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_1731ecb264ce4966ba517250ad49ce4b(castedCommand);
                    break;
                case _e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818 castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_b29cf77c85a949cf95c7c84b649d2818(castedCommand);
                    break;
                case _e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc castedCommand:
                    ReceiveCommand__e61c5d2dfc4521841997842ff9788719_0f0bd3ed1c5d4c978612ca7d8365fafc(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_e61c5d2dfc4521841997842ff9788719 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
            if (bridge != null)
            {
                bridge.OnLateFixedNetworkUpdate -= SendInputState;
            }
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_e61c5d2dfc4521841997842ff9788719>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
            coherenceInput = input;
            inputBuffer = new InputBuffer<_e61c5d2dfc4521841997842ff9788719>(coherenceInput.InitialBufferSize, coherenceInput.InitialInputDelay, coherenceInput.UseFixedSimulationFrames);
            
            coherenceInput.internalSetButton = SetButton;
            coherenceInput.internalSetAxis = SetAxis;
            coherenceInput.internalSetAxis2D = SetAxis2D;
            coherenceInput.internalSetAxis3D = SetAxis3D;
            coherenceInput.internalSetRotation = SetRotation;
            coherenceInput.internalSetInteger = SetInteger;
            coherenceInput.internalSetString = SetString;
            coherenceInput.internalGetButton = GetButton;
            coherenceInput.internalGetAxis = GetAxis;
            coherenceInput.internalGetAxis2D = GetAxis2D;
            coherenceInput.internalGetAxis3D = GetAxis3D;
            coherenceInput.internalGetRotation = GetRotation;
            coherenceInput.internalGetInteger = GetInteger;
            coherenceInput.internalGetString = GetString;
            coherenceInput.internalRequestBuffer = () => inputBuffer;
            coherenceInput.internalOnInputReceived += OnInput;
            
            if (coherenceInput.UseFixedSimulationFrames)
            {
                bridge.OnLateFixedNetworkUpdate += SendInputState;
            }
        }

        private void SetButton(string name, bool value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis(string name, float value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis2D(string name, Vector2 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis3D(string name, Vector3 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
        }
        
        private void SetRotation(string name, Quaternion value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
        }
        
        private void SetInteger(string name, int value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
        }
        
        private void SetString(string name, string value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input string of name: {name}.");
                    break;
            }
        }
        
        public override void SendInputState()
        {
            if (!coherenceInput.IsProducer || !coherenceInput.IsReadyToProcessInputs || !coherenceInput.IsInputOwner)
            {
                return;
            }

            if (lastAddedFrame != currentSimulationFrame)
            {
                inputBuffer.AddInput(currentInput, currentSimulationFrame);
                lastAddedFrame = currentSimulationFrame;
            }

            while (inputBuffer.DequeueForSending(currentSimulationFrame, out long frameToSend, out _e61c5d2dfc4521841997842ff9788719 input, out bool differs))
            {
                coherenceInput.DebugOnInputSent(frameToSend, input);
                client.SendInput(input, frameToSend, entityId);
            }
        }
        
        private bool ShouldPollCurrentInput(long frame)
        {
            return coherenceInput.IsProducer && coherenceInput.Delay == 0 && frame == currentSimulationFrame;
        }
        
        private bool GetButton(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _e61c5d2dfc4521841997842ff9788719 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private float GetAxis(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _e61c5d2dfc4521841997842ff9788719 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private Vector2 GetAxis2D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _e61c5d2dfc4521841997842ff9788719 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
            
            return Vector2.zero;
        }
        
        private Vector3 GetAxis3D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _e61c5d2dfc4521841997842ff9788719 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
            
            return Vector3.zero;
        }
        
        private Quaternion GetRotation(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _e61c5d2dfc4521841997842ff9788719 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
            
            return Quaternion.identity;
        }
        
        private int GetInteger(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _e61c5d2dfc4521841997842ff9788719 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return 0;
        }
        
        private string GetString(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _e61c5d2dfc4521841997842ff9788719 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return null;
        }
        
        private void OnInput(IEntityInput entityInput)
        {
            var input = (_e61c5d2dfc4521841997842ff9788719)entityInput;
            coherenceInput.DebugOnInputReceived(entityInput.Frame, entityInput);
            inputBuffer.ReceiveInput(input, entityInput.Frame);
        }
    }
}
