// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_903fe190c8617be4e8473c42776348b0_51461ff83e8f48dda8736225d0a21179 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_903fe190c8617be4e8473c42776348b0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_903fe190c8617be4e8473c42776348b0>();
        
        private global::Interactable _903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc_CommandTarget;
        private global::Interactable _903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1_CommandTarget;
        private global::Interactable _903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171_CommandTarget;
        private global::Interactable _903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63_CommandTarget;
        private global::Interactable _903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2_CommandTarget;
        private global::Interactable _903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53_CommandTarget;
        private global::Interactable _903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06_CommandTarget;
        private global::Interactable _903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e_CommandTarget;
        
        private InputBuffer<_903fe190c8617be4e8473c42776348b0> inputBuffer;
        private _903fe190c8617be4e8473c42776348b0 currentInput;
        private long lastAddedFrame = -1;
        private CoherenceInput coherenceInput;
        private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["51461ff83e8f48dda8736225d0a21179"] = new Binding_903fe190c8617be4e8473c42776348b0_51461ff83e8f48dda8736225d0a21179(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_903fe190c8617be4e8473c42776348b0()
        {
            bakedCommandBindings.Add("86c90ed42e4f459abd3e08bdc4e909cc", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc);
            bakedCommandBindings.Add("62027883ac5c41cc8b86835e76811aa1", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1);
            bakedCommandBindings.Add("36a5acd7006a4af3b24ef0fd3515f171", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171);
            bakedCommandBindings.Add("bf75bfb8a4f54b6ea0f9d0245a624e63", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63);
            bakedCommandBindings.Add("e2329d18ca2e4f15bd75f5fe5a0647e2", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2);
            bakedCommandBindings.Add("969299e39ce946de8ee8b82aebb1fc53", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53);
            bakedCommandBindings.Add("ebbb069f56ef4cd8890fdbf24f071b06", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06);
            bakedCommandBindings.Add("12398de6775547ae8870fd9e5517d98e", BakeCommandBinding__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestCollect",
            	"(UnityEngine.GameObject)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc(_903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc_CommandTarget;
			target.RequestCollect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestInspect",
            	"(UnityEngine.GameObject)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1(_903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1 command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1_CommandTarget;
			target.RequestInspect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestMurder",
            	"(UnityEngine.GameObject)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171(_903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171 command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171_CommandTarget;
			target.RequestMurder(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestScare",
            	"(UnityEngine.GameObject)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63(_903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63 command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63_CommandTarget;
			target.RequestScare(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnScare",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2(_903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2 command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2_CommandTarget;
			target.OnScare(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnMurder",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53(_903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53 command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53_CommandTarget;
			target.OnMurder(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnInspect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06(_903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06 command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06_CommandTarget;
			target.OnInspect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnCollect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e,
            	ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e,
            	MessageTarget.All,
            	_903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e(GenericCommandRequestArgs requestArgs)
        {
            var command = new _903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e(command);
        }

        private void ReceiveCommand__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e(_903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e command)
        {
            var target = _903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e_CommandTarget;
			target.OnCollect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_86c90ed42e4f459abd3e08bdc4e909cc(castedCommand);
                    break;
                case _903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1 castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_62027883ac5c41cc8b86835e76811aa1(castedCommand);
                    break;
                case _903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171 castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_36a5acd7006a4af3b24ef0fd3515f171(castedCommand);
                    break;
                case _903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63 castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_bf75bfb8a4f54b6ea0f9d0245a624e63(castedCommand);
                    break;
                case _903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2 castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_e2329d18ca2e4f15bd75f5fe5a0647e2(castedCommand);
                    break;
                case _903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53 castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_969299e39ce946de8ee8b82aebb1fc53(castedCommand);
                    break;
                case _903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06 castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_ebbb069f56ef4cd8890fdbf24f071b06(castedCommand);
                    break;
                case _903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e castedCommand:
                    ReceiveCommand__903fe190c8617be4e8473c42776348b0_12398de6775547ae8870fd9e5517d98e(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_903fe190c8617be4e8473c42776348b0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
            if (bridge != null)
            {
                bridge.OnLateFixedNetworkUpdate -= SendInputState;
            }
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_903fe190c8617be4e8473c42776348b0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
            coherenceInput = input;
            inputBuffer = new InputBuffer<_903fe190c8617be4e8473c42776348b0>(coherenceInput.InitialBufferSize, coherenceInput.InitialInputDelay, coherenceInput.UseFixedSimulationFrames);
            
            coherenceInput.internalSetButton = SetButton;
            coherenceInput.internalSetAxis = SetAxis;
            coherenceInput.internalSetAxis2D = SetAxis2D;
            coherenceInput.internalSetAxis3D = SetAxis3D;
            coherenceInput.internalSetRotation = SetRotation;
            coherenceInput.internalSetInteger = SetInteger;
            coherenceInput.internalSetString = SetString;
            coherenceInput.internalGetButton = GetButton;
            coherenceInput.internalGetAxis = GetAxis;
            coherenceInput.internalGetAxis2D = GetAxis2D;
            coherenceInput.internalGetAxis3D = GetAxis3D;
            coherenceInput.internalGetRotation = GetRotation;
            coherenceInput.internalGetInteger = GetInteger;
            coherenceInput.internalGetString = GetString;
            coherenceInput.internalRequestBuffer = () => inputBuffer;
            coherenceInput.internalOnInputReceived += OnInput;
            
            if (coherenceInput.UseFixedSimulationFrames)
            {
                bridge.OnLateFixedNetworkUpdate += SendInputState;
            }
        }

        private void SetButton(string name, bool value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis(string name, float value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis2D(string name, Vector2 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis3D(string name, Vector3 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
        }
        
        private void SetRotation(string name, Quaternion value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
        }
        
        private void SetInteger(string name, int value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
        }
        
        private void SetString(string name, string value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input string of name: {name}.");
                    break;
            }
        }
        
        public override void SendInputState()
        {
            if (!coherenceInput.IsProducer || !coherenceInput.IsReadyToProcessInputs || !coherenceInput.IsInputOwner)
            {
                return;
            }

            if (lastAddedFrame != currentSimulationFrame)
            {
                inputBuffer.AddInput(currentInput, currentSimulationFrame);
                lastAddedFrame = currentSimulationFrame;
            }

            while (inputBuffer.DequeueForSending(currentSimulationFrame, out long frameToSend, out _903fe190c8617be4e8473c42776348b0 input, out bool differs))
            {
                coherenceInput.DebugOnInputSent(frameToSend, input);
                client.SendInput(input, frameToSend, entityId);
            }
        }
        
        private bool ShouldPollCurrentInput(long frame)
        {
            return coherenceInput.IsProducer && coherenceInput.Delay == 0 && frame == currentSimulationFrame;
        }
        
        private bool GetButton(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _903fe190c8617be4e8473c42776348b0 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private float GetAxis(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _903fe190c8617be4e8473c42776348b0 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private Vector2 GetAxis2D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _903fe190c8617be4e8473c42776348b0 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
            
            return Vector2.zero;
        }
        
        private Vector3 GetAxis3D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _903fe190c8617be4e8473c42776348b0 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
            
            return Vector3.zero;
        }
        
        private Quaternion GetRotation(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _903fe190c8617be4e8473c42776348b0 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
            
            return Quaternion.identity;
        }
        
        private int GetInteger(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _903fe190c8617be4e8473c42776348b0 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return 0;
        }
        
        private string GetString(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _903fe190c8617be4e8473c42776348b0 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return null;
        }
        
        private void OnInput(IEntityInput entityInput)
        {
            var input = (_903fe190c8617be4e8473c42776348b0)entityInput;
            coherenceInput.DebugOnInputReceived(entityInput.Frame, entityInput);
            inputBuffer.ReceiveInput(input, entityInput.Frame);
        }
    }
}
