// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_54f15b9536fdd4f418278553359b147a_556d3192702f46fbbf70d9c4493dd177 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_54f15b9536fdd4f418278553359b147a : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_54f15b9536fdd4f418278553359b147a>();
        
        private global::Interactable _54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a_CommandTarget;
        private global::Interactable _54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace_CommandTarget;
        private global::Interactable _54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f_CommandTarget;
        private global::Interactable _54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953_CommandTarget;
        private global::Interactable _54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f_CommandTarget;
        private global::Interactable _54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4_CommandTarget;
        private global::Interactable _54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b_CommandTarget;
        private global::Interactable _54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["556d3192702f46fbbf70d9c4493dd177"] = new Binding_54f15b9536fdd4f418278553359b147a_556d3192702f46fbbf70d9c4493dd177(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_54f15b9536fdd4f418278553359b147a()
        {
            bakedCommandBindings.Add("bb4d88031fec41e383fc8c27a05fb58a", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a);
            bakedCommandBindings.Add("6145f589a8f14f95b94e5f1bfcaa0ace", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace);
            bakedCommandBindings.Add("e1445547bba24d29bfaf6d86b63fb43f", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f);
            bakedCommandBindings.Add("05dad325a44c432aa57d7adc7fee7953", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953);
            bakedCommandBindings.Add("f3cfa2f929654e7c8f5dac2c58f8088f", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f);
            bakedCommandBindings.Add("14a0a84f9b1747ac94935b432edbc7e4", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4);
            bakedCommandBindings.Add("d4df7b2a66244988bfbe0d419723473b", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b);
            bakedCommandBindings.Add("0afef04cffbf42dcb804d4dc68a09187", BakeCommandBinding__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestCollect",
            	"(UnityEngine.GameObject)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a(_54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a_CommandTarget;
			target.RequestCollect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestInspect",
            	"(UnityEngine.GameObject)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace(_54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace_CommandTarget;
			target.RequestInspect(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestMurder",
            	"(UnityEngine.GameObject)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f(_54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f_CommandTarget;
			target.RequestMurder(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.RequestScare",
            	"(UnityEngine.GameObject)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as UnityEngine.GameObject);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953(_54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953 command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953_CommandTarget;
			target.RequestScare(bridge.EntityIdToGameObject(command.initiatingPlayer));
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnScare",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f(_54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f_CommandTarget;
			target.OnScare(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnMurder",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4(_54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4 command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4_CommandTarget;
			target.OnMurder(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnInspect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b(_54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b_CommandTarget;
			target.OnInspect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        private void BakeCommandBinding__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187_CommandTarget = (global::Interactable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Interactable.OnCollect",
            	"(Coherence.Toolkit.CoherenceSync)",
            	SendCommand__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187,
            	ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187,
            	MessageTarget.All,
            	_54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187(GenericCommandRequestArgs requestArgs)
        {
            var command = new _54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.initiatingPlayer = (Entity)bridge.UnityObjectToEntityId(requestArgs.Args[0] as Coherence.Toolkit.CoherenceSync);

            ReceiveCommand__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187(command);
        }

        private void ReceiveCommand__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187(_54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187 command)
        {
            var target = _54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187_CommandTarget;
			target.OnCollect(bridge.EntityIdToCoherenceSync(command.initiatingPlayer));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_bb4d88031fec41e383fc8c27a05fb58a(castedCommand);
                    break;
                case _54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_6145f589a8f14f95b94e5f1bfcaa0ace(castedCommand);
                    break;
                case _54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_e1445547bba24d29bfaf6d86b63fb43f(castedCommand);
                    break;
                case _54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953 castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_05dad325a44c432aa57d7adc7fee7953(castedCommand);
                    break;
                case _54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_f3cfa2f929654e7c8f5dac2c58f8088f(castedCommand);
                    break;
                case _54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4 castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_14a0a84f9b1747ac94935b432edbc7e4(castedCommand);
                    break;
                case _54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_d4df7b2a66244988bfbe0d419723473b(castedCommand);
                    break;
                case _54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187 castedCommand:
                    ReceiveCommand__54f15b9536fdd4f418278553359b147a_0afef04cffbf42dcb804d4dc68a09187(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_54f15b9536fdd4f418278553359b147a Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_54f15b9536fdd4f418278553359b147a>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
